main/urls.py
import main.views as main
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', main.start_page, name='index'),
    path('recruit/create/', main.recruit_create, name='recruit_create'),
    path('recruit/finish_test/', main.finish_test, name='finish_test'),
    path('recruit/test/<int:pk>/', main.RecruitTest.as_view(), name='recruit_test'),
    path('sith/list/', main.sith_list, name='sith_list'),
    path('sith/detail/<int:pk>/', main.sith_detail, name='sith_detail'),
    path('sith/recruit_test_result/<int:pk>/', main.recruit_test_result, name='recruit_test_result'),
    path('sith/add_recruit/<int:pk_sith>/<int:pk_recruit>/', main.add_recruit, name='add_recruit'),
    path('sith/del_recruit/<int:pk_sith>/<int:pk_recruit>/', main.del_recruit, name='del_recruit'),
]

recruiting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

]

main/models.py
from django.db import models


# Create your models here.
class Planet(models.Model):
    ''' Планета '''
    name = models.CharField('Название планеты', max_length=100)

    def __str__(self):
        return self.name


class Recruit(models.Model):
    ''' Рекрут '''
    name = models.CharField('Имя', max_length=100)
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE, verbose_name='Название планеты')
    age = models.PositiveIntegerField('Возраст')
    email = models.EmailField('Email', max_length=100)

    def __str__(self):
        return self.name


class Sith(models.Model):
    ''' Ситх '''
    name = models.CharField('Имя', max_length=100)
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE)
    recruits = models.ManyToManyField(Recruit, verbose_name='Рекруты этого Ситха', null=True, blank=True)

    def __str__(self):
        return self.name


class QuestionsList(models.Model):
    title = models.CharField('Текст вопроса', max_length=200)

    def __str__(self):
        return self.title


class TestTrial(models.Model):
    '''Тестовые испытания'''
    orden_code = models.CharField('Код ордена', max_length=50)
    questions = models.ManyToManyField(QuestionsList)

    def __str__(self):
        return self.orden_code


class Answer(models.Model):
    '''Ответы рекрута'''
    recruit = models.ForeignKey(Recruit, verbose_name='Рекрут', on_delete=models.CASCADE,
                                related_name='recruit_answers')
    question = models.ForeignKey(QuestionsList, 'Вопрос')
    answer = models.BooleanField('Ответ рекрута', null=True, blank=True)

    def __str__(self):
        return f'Рекрут {self.recruit.name}. Вопрос {self.question.title}. Ответ {self.answer}'

main/forms.py
from django import forms
from main.models import Recruit, Answer


class RecruitForm(forms.ModelForm):
    '''Форма для создания рекрута'''
    class Meta:
        model = Recruit
        fields = ('name', 'planet', 'age', 'email')


class RecruitTestForm(forms.ModelForm):
    '''Форма для генерации списка вопросов теста'''
    class Meta:
        model = Answer
        fields = ('question', 'answer')

    def __init__(self, *args, **kwargs):
        super(RecruitTestForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['question'].widget.attrs['hidden'] = True

main/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView
from main.forms import RecruitForm, RecruitTestForm
from main.models import TestTrial, Answer, Recruit, Sith
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.



def start_page(request):
    '''Стартовый страница'''
    return render(request, 'main/index.html', {'title': 'Рекрутинг ***Добро пожаловать***'})


def recruit_create(request):
    ''' Создание рекрута и вопросов теста для него'''
    recruit = RecruitForm(data=request.POST or None)
    if request.method == 'POST' and recruit.is_valid():
        recruit.save()
        # создаю тестовые вопросы
        # так как о разных тестах речи не шло, беру из базы единственный тест
        test = TestTrial.objects.all().first()
        for question in test.questions.all():
            answer = Answer(recruit_id=recruit.instance.id, question=question)
            answer.save()
        return HttpResponseRedirect(reverse('main:recruit_test', args=[recruit.instance.id]))
    content = {'recruit_form': RecruitForm() if not recruit else recruit}
    return render(request, 'main/create_recruit.html', content)


class RecruitTest(UpdateView):
    '''Реализует получение ответов на вопросы теста'''
    model = Recruit
    fields = []
    success_url = reverse_lazy('main:finish_test')
    template_name = 'main/recruit_test.html'

    def get_context_data(self, **kwargs):
        data = super(RecruitTest, self).get_context_data(**kwargs)
        TestFormSet = inlineformset_factory(Recruit, Answer,
                                            form=RecruitTestForm, extra=0)
        if self.request.POST:
            data['test_form'] = TestFormSet(self.request.POST, instance=self.object)
        else:
            formset = TestFormSet(instance=self.object)
            data['test_form'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        test_form = context['test_form']

        with transaction.atomic():
            self.object = form.save()
            if test_form.is_valid():
                test_form.instance = self.object
                test_form.save()
        return super(RecruitTest, self).form_valid(form)


def finish_test(request):
    '''Выводит страницу после завершения теста'''
    return render(request, 'main/test_finish.html', {'title': 'Тестирование завершено. Ваши ответы приняты!'})


def sith_list(request):
    '''Выводит список Ситхов'''
    content = {'title': 'Выбирите себя из списка',
               'siths': Sith.objects.all()}
    return render(request, 'main/sith_list.html', content)


def sith_detail(request, pk):
    ''' Выводит список всех рекрутов у Ситха'''
    try:
        sith = Sith.objects.get(pk=pk)
    except ObjectDoesNotExist:
        return render(request, 'main/error_page.html')
    shadow_hadns = sith.recruits.all()
    shadow_hadns_count = shadow_hadns.count()
    recruits = Recruit.objects.all().exclude(pk__in=shadow_hadns.values_list('pk'))
    content = {
        'sith': sith,
        'shadow_hadns': shadow_hadns,
        'shadow_hadns_count': shadow_hadns_count,
        'recruits': recruits,
        'title': f'Рекруты ситха "{sith.name}"',
        'max_shadow_hands':settings.MAX_SHADOW_HANDS
    }
    return render(request, 'main/sith_detail.html', content)


def add_recruit(request, pk_sith, pk_recruit):
    '''Добавляет рекрута Ситху'''
    try:
        sith = Sith.objects.get(pk=pk_sith)
        recruit = Recruit.objects.get(pk=pk_recruit)
    except ObjectDoesNotExist:
        return render(request, 'main/error_page.html')
    sith.recruits.add(recruit)
    send_mail(
        'Вас приняли в Руки Теней',
        f'{sith.name} принял Вас в Руки Теней',
        'recruting@mail.com',
        [recruit.email],
        fail_silently=True,
    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def del_recruit(request, pk_sith, pk_recruit):
    '''Удаляет рекрута у Ситха'''
    try:
        sith = Sith.objects.get(pk=pk_sith)
        recruit = Recruit.objects.get(pk=pk_recruit)
    except ObjectDoesNotExist:
        return render(request, 'main/error_page.html')
    sith.recruits.remove(recruit)
    send_mail(
        'Вас исключили из Рук Теней',
        f'{sith.name} исключил Вас из Рук Теней',
        'recruting@mail.com',
        [recruit.email],
        fail_silently=True,
    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def recruit_test_result(request, pk):
    '''Выводит страницу с результатами тестирования'''
    try:
        recruit = Recruit.objects.get(pk=pk)
    except ObjectDoesNotExist:
        return render(request, 'main/error_page.html')
    answers = recruit.recruit_answers.all()
    content = {
        'answers': answers,
        'title': f'Ответы рекрута "{recruit.name}"',
        'next': request.META.get('HTTP_REFERER')
    }
    return render(request, 'main/show_test_result.html', content)

main/templates/main/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
        {% block page_title %}
            {{ title|title }}
        {% endblock %}
    </title>
</head>
<body>
{% block page_content %}

{% endblock %}
</body>
</html>

main/templates/main/create_recruit.html
{% extends 'main/base.html' %}

{% block page_title %}
    Введи свои данные рекрут
{% endblock %}

{% block page_content %}
    <h3>Введи свои данные рекрут</h3>
    <form action="{% url 'main:recruit_create' %}" method="post">
        {% csrf_token %}
        {{ recruit_form.as_p }}
        <input type="submit" value="Далее">
    </form>
{% endblock %}

main/templates/main/error_page.html
{% extends 'main/base.html' %}

{% block page_title %}
    Произошла ошибка
{% endblock %}

{% block page_content %}
    <h3>Произошла ошибка</h3>
    Попробуйте заново.
    <a href="{% url 'main:index' %}">
        На главную
    </a>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block page_title %}
    {{ title }}
{% endblock %}

{% block page_content %}
    <h3>Если ты рекрут, тебе <a href="{% url 'main:recruit_create' %}">
        сюда
    </a></h3>
    ************************************************************<br>
    <h3>Если Вы Ситх, прошу следовать <a href="{% url 'main:sith_list' %}">
        в этом направлении
    </a></h3>
    <br>
    <br>
    Админка<br>
    Логин: admin<br>
    Пароль: admin<br>
{% endblock %}

main/templates/main/recruit_test.html
{% extends 'main/base.html' %}

{% block page_title %}
    Ответь на вопросы
{% endblock %}

{% block page_content %}
    <h3>Ответь на вопросы</h3>

    <form action="" method="post">
        {% csrf_token %}
        {{ test_form.management_form }}
        {% for form in test_form.forms %}
            {% for field in form.visible_fields %}
                {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                {% endif %}
                {{ field.errors.as_ul }}
                {% if field.name == 'question' %}
                    {% if form.instance.question %}
                        {{ form.instance.question }}
                    {% else %}
                        {{ form.data.question }}
                    {% endif %}
                    {{ field }}
                {% endif %}
                {% if field.name == 'answer' %}
                    {{ field }}
                {% endif %}
                <br>
            {% endfor %}
        {% endfor %}
        <button type="submit">Готово</button>
    </form>
{% endblock %}

main/templates/main/show_test_result.html
{% extends 'main/base.html' %}

{% block page_title %}
    {{ title }}
{% endblock %}

{% block page_content %}
    <h3>{{ title }}</h3>
    {% for answer in answers %}
        Вопрос: {{ answer.question.title }}<br>
        {% if answer.answer %}
            Ответ: Да
        {% elif answer.answer == False %}
            Ответ: Нет
        {% else %}
            Ответ: Не определился
        {% endif %}
        <br>
        --------------------------
        <br>
    {% endfor %}
    <a href="{{ next }}"> Назад </a>
{% endblock %}

main/templates/main/sith_detail.html
{% extends 'main/base.html' %}

{% block page_title %}
    {{ title }}
{% endblock %}

{% block page_content %}
    {% if shadow_hadns_count != 0 %}
        <h3>Ваши Руки Tеней:</h3>
        {% for shadow_hadn in shadow_hadns %}
            {{ shadow_hadn.name }} с планеты {{ shadow_hadn.planet.name }}<br>
            <a href="{% url 'main:del_recruit' pk_sith=sith.pk pk_recruit=shadow_hadn.pk %}">
                Отказать в сотрудничестве
            </a>
            <br>------------------------------<br>
        {% endfor %}
    {% else %}
        <h3>У вас нет Рук Теней. Можете выбрать в списке ниже {{ max_shadow_hands }}x.</h3>
        ------------------------------<br>
    {% endif %}

    <h3>**** Список всех свободных рекрутов ****</h3>
    {% for recruit in recruits %}
        {{ recruit.name }} с планеты {{ recruit.planet.name }}<br>
        <a href="{% url 'main:recruit_test_result' pk=recruit.pk %}">
            Посмотреть результаты теста
        </a>
        <br>
        {% if shadow_hadns_count < max_shadow_hands %}
            <a href="{% url 'main:add_recruit' pk_sith=sith.pk pk_recruit=recruit.pk %}">
                Принять в Руки Теней
            </a>
        {% else %}
            У Вас уже {{ max_shadow_hands }} Руки Тени. Откажитесь от одного из рекрутов, что бы принять этого.
        {% endif %}
        <br>------------------------------<br>

    {% endfor %}
    <br>
    <a href="{% url 'main:index' %}">
        На главную
    </a>
{% endblock %}

main/templates/main/sith_list.html
{% extends 'main/base.html' %}

{% block page_title %}
    {{ title }}
{% endblock %}

{% block page_content %}
    <h3>Выбирите себя из списка</h3>
    {% for sith in siths %}
        <a href="{% url 'main:sith_detail' sith.pk %}">
            {{ sith.name }} с планеты {{ sith.planet }}. <br>
            Количество Рук Теней {{ sith.recruits.all.count }}
        </a>
        <br>***
        <br>
    {% endfor %}
    <br>
    <h3>Ситхи у которых более одной Руки Теней</h3>
    {% for sith in siths %}
        {% if sith.recruits.all.count > 1 %}
            {{ sith.name }} с планеты {{ sith.planet }}.
            <br>
        {% endif %}
    {% endfor %}
    <br>
    <a href="{% url 'main:index' %}">
        На главную
    </a>
{% endblock %}

main/templates/main/test_finish.html
{% extends 'main/base.html' %}

{% block page_title %}
    {{ title }}
{% endblock %}

{% block page_content %}
    <h3>Ваши ответы приняты!</h3>
    Ожидайте решения на почту
    <a href="{% url 'main:index' %}">
        На главную
    </a>
{% endblock %}